work_dir: ./work_dir/recognition/iMiGUE/TCN_VAE_TEST

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ./data/iMiGUE/imigue_polar/train_data.npy
  label_path: ./data/iMiGUE/imigue_polar/train_label.pkl
test_feeder_args:
  data_path: ./data/iMiGUE/imigue_polar/test_data.npy
  label_path: ./data/iMiGUE/imigue_polar/test_label.pkl

# model
model: net.tcn_vae.TCN_VAE
model_args:
  en_input_size: 100
  en_num_channels: [50, 1]
  de_num_channels: [1, 25, 50, 75]
  output_size: 100
  num_person: 1
  in_channels: 2
  num_point: 20

#optim
weight_decay: 0.0001
base_lr: 0.001
step: [300, 350]

# training
device: [0]
batch_size: 32
test_batch_size: 32
num_epoch: 400



