work_dir: ./work_dir/recognition/iMiGUE/MSTGCN_VAE_RAWDATA_SMG_TEST

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ./data/iMiGUE/imigue_afterdebug_processed/train_data.npy
  label_path: ./data/iMiGUE/imigue_afterdebug_processed/train_label.pkl
test_feeder_args:
  data_path: ./data/SMG/smg_test/test_data.npy
  label_path: ./data/SMG/smg_test/test_label.pkl

# model
model: lastnet.msg3d.MSTCN_VAE
model_args:
  graph: 'graph.imigue.AdjMatrixGraph'
  classifeature: 100
  num_gcn_scales: 13
  num_g3d_scales: 6
  de_num_channels: [10, 25, 50]
  output_size: 100
  num_person: 1
  in_channels: 3
  num_point: 20

#optim
weight_decay: 0.0001
base_lr: 0.001
step: [300, 350]

# training
device: [0]
batch_size: 32
test_batch_size: 32
num_epoch: 400

