work_dir: ./work_dir/recognition/iMiGUE/MSTCN_VAE_LINEAR_TEST

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ./data/iMiGUE/imigue_polar/train_data.npy
  label_path: ./data/iMiGUE/imigue_polar/train_label.pkl
test_feeder_args:
  data_path: ./data/iMiGUE/imigue_polar/test_data.npy
  label_path: ./data/iMiGUE/imigue_polar/test_label.pkl

# model
model: net.ms_tcn_vae_linear.MSTCN_VAE
model_args:
  C: 2
  num_output: 96
  de_num_channels: [1, 50]
  output_size: 100
  num_person: 1
  in_channels: 2
  num_point: 20

#optim
weight_decay: 0.00001
base_lr: 0.0001
step: [400, 450]

# training
device: [0]
batch_size: 32
test_batch_size: 32
num_epoch: 500



